version: 2
jobs:
  linux_build:
    docker:
      - image: "circleci/rust:1.33.0"
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Create workspace
          command: mkdir -p /tmp/workspace
      - run:
          name: Install required dependencies
          command: |
            sudo apt update
            sudo apt install -y musl musl-tools
      - run:
          name: Install build target
          command: rustup target add x86_64-unknown-linux-musl
      - run:
          name: Build executable
          command: cargo build --release --target x86_64-unknown-linux-musl
      - run:
          name: Copy build to workspace
          command: cp -R target /tmp/workspace/
      - persist_to_workspace:
          root: /tmp/workspace/
          paths: target/x86_64*
      - store_artifacts:
          path: target/x86_64-unknown-linux-musl/release/deployment-cli
  macos_build:
    docker:
      - image: "circleci/rust:1.33.0"
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Create workspace
          command: mkdir -p /tmp/workspace
      - run:
          name: Install required dependencies
          command: |
            sudo apt update
            sudo apt install wget git clang
      - run:
          name: Install build target
          command: rustup target add x86_64-apple-darwin
      - run:
          name: Install osxcross
          command: sudo ./buildscripts/setup_osxcross.sh
      - run:
          name: Copy cargo configuration to the expected path
          command: |
            mkdir .cargo
            cp buildscripts/cargo_config .cargo/config
      - run:
          name: Build executable
          environment:
            TARGET_CC: '/usr/local/osx-ndk-x86/bin/x86_64-apple-darwin15-cc'
            PKG_CONFIG_ALLOW_CROSS: '1'
          command: cargo build --release --target x86_64-apple-darwin
      - run:
          name: Copy build to workspace
          command: cp -R target /tmp/workspace/
      - persist_to_workspace:
          root: /tmp/workspace/
          paths: target/x86_64*
      - store_artifacts:
          path: target/x86_64-apple-darwin/release/deployment-cli
  github_release:
    docker:
      - image: "circleci/golang:1.8"
    steps:
      - run:
          name: Install ghr
          command: go get github.com/tcnksm/ghr
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Compress files
          command: |
            mkdir artifacts
            cat /tmp/workspace/x86_64-unknown-linux-musl/release/deployment-cli | xz > artifacts/deployment-cli-${CIRCLECI_TAG}-x86_64-unknown-linux-musl.xz
            cat /tmp/workspace/x86_64-apple-darwin/release/deployment-cli | xz > artifacts/deployment-cli-${CIRCLECI_TAG}-x86_64-apple-darwin.xz
      - run:
          name: Download and mark deployment-cli as executable
          command: |
            wget https://49-180783237-gh.circle-artifacts.com/0/home/circleci/project/target/x86_64-unknown-linux-musl/release/deployment-cli
            chmod +x deployment-cli
      - run:
          name: Create release
          command: ghr -t $(./deployment-cli token) -u x-access-token -r ${CIRCLECI_PROJECT_REPONAME} -c ${CIRCLECI_SHA1} -delete ${CIRCLECI_TAG} artifacts/

workflows:
  version: 2
  build_and_release:
    jobs:
      - linux_build
      - macos_build
      - github_release:
          requires:
            - linux_build
            - macos_build
          filters:
            tags:
              only: /^v.+/
only: master
