version: 2
jobs:
  build:
    docker:
      - image: "circleci/rust:1.33.0"
    steps:
      - checkout
      - run:
          name: Install required dependencies
          command: |
            sudo apt update
            sudo apt install -y musl musl-tools openssl
      - run:
          name: Install build target
          command: rustup target add x86_64-unknown-linux-musl
      - run:
          name: Build executable
          command: cargo build --release --target x86_64-unknown-linux-musl
      - store_artifacts:
          path: target/x86_64-unknown-linux-musl/release/deployment-cli
only: master
