version: 2
jobs:
  linux_build:
    docker:
      - image: "circleci/rust:1.33.0"
    steps:
      - checkout
      - run:
          name: Install required dependencies
          command: |
            sudo apt update
            sudo apt install -y musl musl-tools
      - run:
          name: Install build target
          command: rustup target add x86_64-unknown-linux-musl
      - run:
          name: Build executable
          command: cargo build --release --target x86_64-unknown-linux-musl
      - store_artifacts:
          path: target/x86_64-unknown-linux-musl/release/deployment-cli
  macos_build:
    docker:
      - image: "circleci/rust:1.33.0"
    steps:
      - checkout
      - run:
          name: Install required dependencies
          command: |
            sudo apt update
            sudo apt install wget git clang
      - run:
          name: Install build target
          command: rustup target add x86_64-apple-darwin
      - run:
          name: Install osxcross
          command: sudo ./buildscripts/setup_osxcross.sh
      - run:
          name: Copy cargo configuration to the expected path
          command: |
            mkdir .cargo
            cp buildscripts/cargo_config .cargo/config
      - run:
          name: Build executable
          environment:
            TARGET_CC: '/usr/local/osx-ndk-x86/bin/x86_64-apple-darwin15-cc'
            PKG_CONFIG_ALLOW_CROSS: '1'
          command: cargo build --release --target x86_64-apple-darwin
      - store_artifacts:
          path: target/x86_64-apple-darwin/release/deployment-cli
workflows:
  version: 2
  linux:
    jobs:
      - linux_build
  macos:
    jobs:
      - macos_build
only: master
